envname: acdc_env
ignore_kspace: False
ignore_image: False
dev_mode: False
val_shuffle: False
num_workers: 3
image_shape: [256, 256]
kspace_shape: [256, 256]
sampled_indices: [0, 255]
in_channels: 1
#coil_type: sc
dataset: acdc
scale_reward: True
reward_mode: 10
penalty_factor: -1
delay_step: 7
parallel_init: True
train_fixed_budget: False
eval_fixed_budget: True
batch_size: ???
val_batch_size: 80
test_batch_size: 80
observation_space: [1, 256, 256]
use_weighted_sampler: True
datadir: /****/dataset/generated_files
split_csv_file: /****/dataset/metadata_acdc.csv
train_sampler_filename: /*****/dataset/meta_data.p
